### ISSUE TITLE
Error: Exception: Please wait at least 10 seconds before attempting another login.

### ISSUE THREAD

**Issue by nurkka** [adrianbj/ProtectedMode#2]
Thanks for the great module!

While testing, I spotted an error: When repeatedly trying to login with a wrong password, PW throws an exception: »Error: Exception: Please wait at least 10 seconds before attempting another login.«. 

With $config->debug = true; the typical verbose error screen is displayed.
With $config->debug = false; I get an »Internal Server Error«-page.

I believe the exception is a default behaviour of Processwire which the module currently doesn't take care of.

**Comment by adrianbj** [comment]
Hi @nurkka - sorry I missed this issue!

Honestly I am not really sure if the module can do anything about this since I am using ProcessWire's login routine. I know it's ugly, but at least it's secure. Did you by chance look into how this might be made more friendly?

**Comment by adrianbj** [comment]
@nurkka - I haven't heard back from you, so I am going to close this, but if you have an idea how this could be improved, please let me know.
