### ISSUE TITLE
FR: Adding list of allowable roles

### ISSUE THREAD

**Issue by lesaff** [adrianbj/ProtectedMode#3]
@adrianbj, we're using this a lot on our projects now. Love it! It's good for staging env.

Is it possible to add a list of allowable roles for this module? I want to be able to limit who can/cannot login via ProtectedMode

Cheers
Rudy

**Comment by adrianbj** [comment]
Hi @lesaff 

I have added this via: https://github.com/adrianbj/ProtectedMode/commit/84c2a87373897ed99b9ee86c7a4d0df3e9f5a3fa

Please let me know if you find any problems.

**Comment by lesaff** [comment]
Whoa, that's pretty quick!

Works as expected 👍 

Thx Adrian
